version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/quiz_system?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongodb_data: 